default: true
line-length: false
single-title: false
no-inline-html:
  allowed_elements:
  - a
  - details
  - summary
  - Highlight
blanks-around-lists: false

# no-inline-html: HugoのShort Codesが誤検知されてしまうので無効化
MD033: false