filters:
  allowlist:
    allow:
      - GitHub Copilot
rules: 
  preset-ja-technical-writing:
    sentence-length: 
      max: 100
      skipPatterns: 
      - "/\(.*\)/"
    ja-no-mixed-period: 
      allowPeriodMarks: 
      - ":::"
    max-kanji-continuous-len: 
      max: 6
      allow: 
  preset-jtf-style: true
  textlint-rule-preset-ja-spacing: true
  prh: 
    rulePaths: 
    - ./prh.yaml