filters:
  comments:
    true
  allowlist:
    allow:
      - GitHub Copilot
rules:
  preset-ja-technical-writing:
    sentence-length:
      max: 100
      skipPatterns:
        - /\(.*\)/
    ja-no-mixed-period:
      periodMark: "。"
      allowPeriodMarks:
        - ":::"
    max-kanji-continuous-len:
      max: 6
    no-exclamation-question-mark: false
    ja-no-redundant-expression: false
    no-mix-dearu-desumasu: false
  period-in-list-item: true
  preset-jtf-style: true
  textlint-rule-preset-ja-spacing: true
  prh:
    rulePaths:
    - ./prh.yaml
